/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pendaftaran;

/**
 *
 * @author USER
 */

import index.index;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.newpackage.Koneksi;

public class lihat_pendaftaran extends javax.swing.JFrame {
    
    String idPendaftaran = "";
    private javax.swing.ButtonGroup bgStatus;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(lihat_pendaftaran.class.getName());

    /**
     * Creates new form lihat_pendaftaran
     */
    public lihat_pendaftaran() {
        initComponents();
        tampilData();
        warnaStatus();
        bgStatus = new javax.swing.ButtonGroup();

    bgStatus.add(jRadioButton1);
    bgStatus.add(jRadioButton2);
    setSize(1000,600);
    setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Status : ");

        jRadioButton1.setText("Aktif");
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);

        jRadioButton2.setText("Tidak Aktif");
        jRadioButton2.addActionListener(this::jRadioButton2ActionPerformed);

        jButton1.setText("Ubah");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("< Kembali");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel1))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();

        idPendaftaran =
            jTable1.getValueAt(baris, 0).toString();

        bgStatus.clearSelection();

        String status =
            jTable1.getValueAt(baris, 9).toString();

        if(status.equals("Aktif")){
            jRadioButton1.setSelected(true);
        }else{
            jRadioButton2.setSelected(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

        if (idPendaftaran.equals("")) {

            JOptionPane.showMessageDialog(null,
                    "Pilih data terlebih dahulu");

            return;
        }

        String status = "";

        if (jRadioButton1.isSelected()) {

            status = "Aktif";

        } else if (jRadioButton2.isSelected()) {

            status = "Tidak Aktif";

        } else {

            JOptionPane.showMessageDialog(null,
                    "Pilih status");

            return;
        }

        Connection conn = koneksi.newpackage.Koneksi.getConnection();

        String sql =
                "UPDATE pendaftaran "
                + "SET status=? "
                + "WHERE id_pendaftaran=?";

        java.sql.PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setString(1, status);
        pst.setString(2, idPendaftaran);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null,
                "Status berhasil diubah");

        tampilData();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null,
                e.getMessage());

    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new index().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new lihat_pendaftaran().setVisible(true));
    }
    
    private void tampilData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Pendaftaran");
    model.addColumn("ID Siswa");
    model.addColumn("Nama Siswa");
    model.addColumn("ID Orang Tua");
    model.addColumn("Nama Ayah");
    model.addColumn("Nama Ibu");
    model.addColumn("Kelas");
    model.addColumn("Pengajar");
    model.addColumn("Tanggal Daftar");
    model.addColumn("Status");

    try {

        Connection conn = koneksi.newpackage.Koneksi.getConnection();

        String sql =
                "SELECT "
                + "p.id_pendaftaran, "
                + "s.id_siswa, "
                + "s.nama_siswa, "
                + "o.id_orang_tua, "
                + "o.nama_ayah, "
                + "o.nama_ibu, "
                + "k.nama_kelas, "
                + "k.pengajar, "
                + "p.tanggal_daftar, "
                + "p.status "
                + "FROM pendaftaran p "
                + "INNER JOIN siswa s "
                + "ON p.id_siswa = s.id_siswa "
                + "INNER JOIN orang_tua o "
                + "ON p.id_orang_tua = o.id_orang_tua "
                + "INNER JOIN kelas k "
                + "ON p.id_kelas = k.id_kelas";

        Statement st = conn.createStatement();

        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {

            model.addRow(new Object[]{

                rs.getString("id_pendaftaran"),
                rs.getString("id_siswa"),
                rs.getString("nama_siswa"),
                rs.getString("id_orang_tua"),
                rs.getString("nama_ayah"),
                rs.getString("nama_ibu"),
                rs.getString("nama_kelas"),
                rs.getString("pengajar"),
                rs.getString("tanggal_daftar"),
                rs.getString("status")

            });

        }

        jTable1.setModel(model);
        warnaStatus();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null,
                "Gagal Menampilkan Data : "
                + e.getMessage());

    }
}
    
    private void warnaStatus() {

    jTable1.setDefaultRenderer(Object.class,
            new javax.swing.table.DefaultTableCellRenderer() {

        @Override
        public java.awt.Component getTableCellRendererComponent(
                javax.swing.JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {

            java.awt.Component c =
                    super.getTableCellRendererComponent(
                            table,
                            value,
                            isSelected,
                            hasFocus,
                            row,
                            column);

            String status =
                    table.getValueAt(row, 9).toString();

            if (!isSelected) {

                if (status.equals("Tidak Aktif")) {

                    c.setBackground(
                            java.awt.Color.PINK);

                } else {

                    c.setBackground(
                            java.awt.Color.WHITE);

                }

            }

            return c;
        }
    });

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
